<div id ="navBar">
			<h2>Lab Assignments</h2>
			<ul>
				<li> <a href="http://helios.ite.gmu.edu/~kislam8/IT207/homepage.php">Home</a></li>
				<li> <a href="http://helios.ite.gmu.edu/~kislam8/IT207/assignment1.html">Assignment 1</a></li>
				<li> Assignment 3</li>
				<li> Assignment 4</li>
			</ul>
			<h3>Lab Practica</h3>
			<ul>
				<li> Practicum 1</li>
				<li> Practicum 2</li>
			</ul>
</div>